apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab-docs
  namespace: homelab-docs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - homelab.eurusik.com
    secretName: homelab-docs-tls
  rules:
  - host: homelab.eurusik.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homelab-docs
            port:
              number: 80
